list.files()
lab1 <- read.csv("Lab_1.csv", header=TRUE)
attach(lab1)
lab1 <- aov(Bead.number~Bead.color)
summary(lab1)
#We fail to reject the null hypothesis, and the bead number is the same across all bead colors (p-value > 0.05).

list.files()
lab2 <- read.csv("Lab_2.csv", header=TRUE)
attach(lab2)
cor.test(Tide_ft,Seals)
#There is a significant negative correlation between the height of the tide and number of seals (t=5.1705, df=112, p-value<0.001)

list.files()
lab3 <- read.csv("Lab_3.csv", header=TRUE)
attach(lab3)
cor.test(depth_m,salinity_pss)
#There is a significant positive correlation between the depth and the salinity of the water (t=4.872, df=593, p-value<0.001)

list.files()
lab4 <- read.csv("Lab_4.csv", header=TRUE)
attach(lab4)
var.test(PVC~Habitat, alternative=c("two.sided"), ratio=1)
#We fail to reject the null hypothesis, and the variance between the two groups is the same (p-value=0.2762)
t.test(PVC~Habitat, alternative=c("two.sided"), paired=FALSE, var.equal=TRUE)
#We reject the null hypothesis, and there is no significant difference between the two habitat types (t=5.9398, df=14, p-value<0.05)

list.files()
lab5 <- read.csv("Lab_55.csv", header=TRUE)
attach(lab5)
var.test(Zoneofinhibition~Bacteriatype, alternative=c("two.sided"), ratio=1)
#We fail to reject the null hypothesis, and the variance between the two groups is the same (p-value=0.9161)
t.test(Zoneofinhibition~Bacteriatype, alternative=c("two.sided"), paired=FALSE, var.equal=TRUE)
#We failed to reject the null hypothesis, and there is a significant difference between the two bacteria types (t=-0.27362, df=10, p-value=0.7899)
