list.files()
lab7 <- read.csv("BIO263.Lab7.ThursdayAlex.csv", header=TRUE)
attach(lab7)
var.test(Shannon_Index ~ Location, alternative=c("two.sided"), ratio=1)
#Variance between the two groups is the same (p-value>0.05)
t.test(Shannon_Index ~ Location, alternative=c("two.sided"), paired=FALSE, var.equal=TRUE)
#We fail to reject the null hypothesis, that there is a significant difference in the variances between the two groups (t=-0.96508, df=10, p-value=0.3573)
library(ggplot2)
ggplot(lab7, aes(x=Location, y=Shannon_Index)) + geom_boxplot() + theme_classic() + labs(x="Location", y="Shannon Index (H')")
